import { lazy } from "react";

export const Home = lazy(() => import("../pages/home"))
export const Layout = lazy(() => import("../pages/layout/layout"))
export const Heder = lazy(() => import("../pages/heder/heder"))
export const Footer = lazy(() => import("../pages/footer/footer"))
export const Abaut = lazy(() => import("../pages/about/about"))
export const Contact = lazy(() => import("../pages/contact/contact"))
export const SignUp = lazy(() => import("../pages/sign up/signup"))
export const SwiperHome = lazy(() => import("../pages/companets/swiperHome/swiper"))
export const FlashSalesTimer = lazy(() => import("./companets/timer/timer"))
export const SwiperProduct = lazy(() => import("./companets/swiperProduct/swiperProduct"))
export const CategoriProduct = lazy(() => import("./companets/categoriProduct/categoriProduct"))
export const Login = lazy(() => import("./login/login"))
export const Account = lazy(() => import("./account/account"))
export const Order = lazy(() => import("./order/order"))
export const SellingProduct = lazy(() => import("./companets/sellingProduct/sellingProduct"))
export const CategoriesBySales= lazy(() => import("./companets/categoriesBySalese/categoriesBySales"))
export const OurProduct= lazy(() => import("./companets/ourproduct/ourProduct"))
export const ExploreOurProducts= lazy(() => import("./companets/exploreOurProducts/exploreOurProducts"))
export const AddTocart= lazy(() => import("./companets/addTocart/addTocart"))
export const InfoPrioduct= lazy(() => import("./companets/infoPrioduct/infoPrioduct"))
export const Checkout= lazy(() => import("./checkout/checkout"))
export const Wishlist= lazy(() => import("./wishlist/wishlist"))